FROM ubuntu AS image

RUN apt-get -y update
RUN apt-get -y install sudo

RUN apt-get -y install wget

RUN sudo apt update
RUN sudo apt install build-essential -y

RUN wget https://sourceforge.net/projects/ion-dtn/files/ion-open-source-4.1.0.tar.gz/download

RUN tar xvzf download

WORKDIR /ion-open-source-4.1.0

RUN ./configure

RUN make

RUN sudo make install

RUN sudo ldconfig

RUN rm killm

RUN ln -s /bin/true killm

WORKDIR /ion-open-source-4.1.0/tests
